version: '2'

services:
  server:
    container_name: converter
    build: .
    image: cameric/8weike-converter:v1
    ports:
      - 5000:8080
    volumes:
      - ./server:/srv/cSERVER
      - /srv/cSERVER/node_modules
